# Generated by Django 4.1.3 on 2022-11-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
    ]
