# Generated by Django 4.1.4 on 2023-03-20 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0007_post_users_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='users_favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
